//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizare.
        /// </summary>
        public static string actualizareBtn {
            get {
                return ResourceManager.GetString("actualizareBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActualizareCantitate.
        /// </summary>
        public static string ActualizareCantitate {
            get {
                return ResourceManager.GetString("ActualizareCantitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdaugareCategorie.
        /// </summary>
        public static string AdaugareCategorie {
            get {
                return ResourceManager.GetString("AdaugareCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdaugareProdus.
        /// </summary>
        public static string AdaugareProdus {
            get {
                return ResourceManager.GetString("AdaugareProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfisareUtilizatori.
        /// </summary>
        public static string AfisareUtilizatori {
            get {
                return ResourceManager.GetString("AfisareUtilizatori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iesire.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logare.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugare.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate disponibila.
        /// </summary>
        public static string cantitateCumparareLbl {
            get {
                return ResourceManager.GetString("cantitateCumparareLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate de cumparat.
        /// </summary>
        public static string cantitatecumparatLbl {
            get {
                return ResourceManager.GetString("cantitatecumparatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate noua: .
        /// </summary>
        public static string cantitateLbl {
            get {
                return ResourceManager.GetString("cantitateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string categorieAddLbl {
            get {
                return ResourceManager.GetString("categorieAddLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salveaza.
        /// </summary>
        public static string categorieBtn {
            get {
                return ResourceManager.GetString("categorieBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie noua: .
        /// </summary>
        public static string categorieLbl {
            get {
                return ResourceManager.GetString("categorieLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de categorii:.
        /// </summary>
        public static string catlbl {
            get {
                return ResourceManager.GetString("catlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauta.
        /// </summary>
        public static string cautareBtn {
            get {
                return ResourceManager.GetString("cautareBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumirea produsului cautat:.
        /// </summary>
        public static string cautareProdLbl {
            get {
                return ResourceManager.GetString("cautareProdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CautareProduse.
        /// </summary>
        public static string CautareProduse {
            get {
                return ResourceManager.GetString("CautareProduse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatorul cautat:.
        /// </summary>
        public static string cautareUTILIZATORLbl {
            get {
                return ResourceManager.GetString("cautareUTILIZATORLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumpara.
        /// </summary>
        public static string cumparaBtn {
            get {
                return ResourceManager.GetString("cumparaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumparare.
        /// </summary>
        public static string Cumparare {
            get {
                return ResourceManager.GetString("Cumparare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire:.
        /// </summary>
        public static string CumpararedenumireLbl {
            get {
                return ResourceManager.GetString("CumpararedenumireLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID produs: .
        /// </summary>
        public static string idLbl {
            get {
                return ResourceManager.GetString("idLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afisare istoric vanzari.
        /// </summary>
        public static string istoricLbl {
            get {
                return ResourceManager.GetString("istoricLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate.
        /// </summary>
        public static string lblCantitate {
            get {
                return ResourceManager.GetString("lblCantitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Expirare.
        /// </summary>
        public static string lblDataExpirare {
            get {
                return ResourceManager.GetString("lblDataExpirare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Intrare.
        /// </summary>
        public static string lblDataIntrare {
            get {
                return ResourceManager.GetString("lblDataIntrare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire.
        /// </summary>
        public static string lblDenumire {
            get {
                return ResourceManager.GetString("lblDenumire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere.
        /// </summary>
        public static string lblDescriere {
            get {
                return ResourceManager.GetString("lblDescriere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUN VENIT.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola:.
        /// </summary>
        public static string lblParola {
            get {
                return ResourceManager.GetString("lblParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ai cont? Inregistrare:.
        /// </summary>
        public static string lblUitareParola {
            get {
                return ResourceManager.GetString("lblUitareParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificare parola:.
        /// </summary>
        public static string lblUitatParola {
            get {
                return ResourceManager.GetString("lblUitatParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator:.
        /// </summary>
        public static string lblusername {
            get {
                return ResourceManager.GetString("lblusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizualizare produse disponibile.
        /// </summary>
        public static string produseBtn {
            get {
                return ResourceManager.GetString("produseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afisare lista utilizatori.
        /// </summary>
        public static string utilizatoriLbl {
            get {
                return ResourceManager.GetString("utilizatoriLbl", resourceCulture);
            }
        }
    }
}
