//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proiect2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Apple_Green_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Apple-Green.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Apple_Red_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Apple-Red.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Apple_Yellow_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Apple-Yellow.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Avocado_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Avocado.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Blackcurrant_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Blackcurrant.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Grape_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Grape.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Kiwifruit_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Kiwifruit.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Pineapple_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Pineapple.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Strawberry_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Strawberry.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconarchive_Fruit_Soft_Illustration_Watermelon_512 {
            get {
                object obj = ResourceManager.GetObject("Iconarchive-Fruit-Soft-Illustration-Watermelon.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paomedia_Small_N_Flat_Profile_512 {
            get {
                object obj = ResourceManager.GetObject("Paomedia-Small-N-Flat-Profile.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paomedia_Small_N_Flat_Search_512 {
            get {
                object obj = ResourceManager.GetObject("Paomedia-Small-N-Flat-Search.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paomedia_Small_N_Flat_Sign_add_512 {
            get {
                object obj = ResourceManager.GetObject("Paomedia-Small-N-Flat-Sign-add.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paomedia_Small_N_Flat_Sign_delete_512 {
            get {
                object obj = ResourceManager.GetObject("Paomedia-Small-N-Flat-Sign-delete.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paomedia_Small_N_Flat_Sign_info_512 {
            get {
                object obj = ResourceManager.GetObject("Paomedia-Small-N-Flat-Sign-info.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
